const types = {
  FILE: 'FILE',
  DIRECTORY: 'DIRECTORY',
  SYMBOLICLINK: 'SYMBOLICLINK',
  FIFO: 'FIFO',
  SOCKET: 'SOCKET',
  BLOCKDEVICE: 'BLOCKDEVICE',
  CHARACTERDEVICE: 'CHARACTERDEVICE',
  UNKNOWN: 'UNKNOWN',
};

module.exports = {
  types,
}; 

